"""Shared language mappings for OCR and transcription pages."""

# Display name -> language code used by Whisper/WhisperX in Transcribe.
TRANSCRIBE_LANGUAGE_MAPPING = {
    "English": "en",
    "German": "de",
    "French": "fr",
    "Spanish": "es",
    "Italian": "it",
    "Swiss German": "ch_de",
    "Swiss German (Flurin Turbo)": "ch_de_flurin",
    "Japanese": "ja",
    "Chinese": "zh",
    "Dutch": "nl",
    "Ukrainian": "uk",
    "Portuguese": "pt",
    "Arabic": "ar",
    "Czech": "cs",
    "Russian": "ru",
    "Polish": "pl",
    "Hungarian": "hu",
    "Finnish": "fi",
    "Persian": "fa",
    "Greek": "el",
    "Turkish": "tr",
    "Danish": "da",
    "Hebrew": "he",
    "Vietnamese": "vi",
    "Korean": "ko",
    "Urdu": "ur",
    "Telugu": "te",
    "Hindi": "hi",
    "Catalan": "ca",
    "Malayalam": "ml",
    "Norwegian Bokmål": "no",
    "Norwegian Nynorsk": "nn",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Croatian": "hr",
    "Romanian": "ro",
    "Basque": "eu",
    "Galician": "gl",
    "Georgian": "ka",
    "Latvian": "lv",
    "Tagalog": "tl",
    "Swedish": "sv",
}

TRANSCRIBE_LANGUAGE_CODE_TO_NAME = {
    code: name for name, code in TRANSCRIBE_LANGUAGE_MAPPING.items()
}

# ---------------------------------------------------------------------------
# Translation language mapping.
#
# Keys are user-facing display names.
# Values are the NLLB / FLORES-200 BCP-47 codes used by facebook/nllb-200-*.
# For other backends (MarianMT / OPUS-MT, MADLAD-400, Ollama-LLM) a small
# adapter converts these codes into whatever the backend expects.
# ---------------------------------------------------------------------------
TRANSLATE_LANGUAGE_MAPPING = {
    "English": "eng_Latn",
    "German": "deu_Latn",
    "French": "fra_Latn",
    "Italian": "ita_Latn",
    "Spanish": "spa_Latn",
    "Portuguese": "por_Latn",
    "Dutch": "nld_Latn",
    "Danish": "dan_Latn",
    "Swedish": "swe_Latn",
    "Norwegian Bokmål": "nob_Latn",
    "Finnish": "fin_Latn",
    "Polish": "pol_Latn",
    "Czech": "ces_Latn",
    "Slovak": "slk_Latn",
    "Slovenian": "slv_Latn",
    "Croatian": "hrv_Latn",
    "Serbian (Cyrillic)": "srp_Cyrl",
    "Bosnian": "bos_Latn",
    "Bulgarian": "bul_Cyrl",
    "Romanian": "ron_Latn",
    "Hungarian": "hun_Latn",
    "Greek": "ell_Grek",
    "Turkish": "tur_Latn",
    "Russian": "rus_Cyrl",
    "Ukrainian": "ukr_Cyrl",
    "Belarusian": "bel_Cyrl",
    "Arabic (MSA)": "arb_Arab",
    "Hebrew": "heb_Hebr",
    "Persian": "pes_Arab",
    "Urdu": "urd_Arab",
    "Hindi": "hin_Deva",
    "Bengali": "ben_Beng",
    "Tamil": "tam_Taml",
    "Telugu": "tel_Telu",
    "Chinese (Simplified)": "zho_Hans",
    "Chinese (Traditional)": "zho_Hant",
    "Japanese": "jpn_Jpan",
    "Korean": "kor_Hang",
    "Vietnamese": "vie_Latn",
    "Thai": "tha_Thai",
    "Indonesian": "ind_Latn",
    "Malay": "zsm_Latn",
    "Swahili": "swh_Latn",
    "Basque": "eus_Latn",
    "Catalan": "cat_Latn",
    "Galician": "glg_Latn",
    "Latvian": "lvs_Latn",
    "Lithuanian": "lit_Latn",
    "Estonian": "est_Latn",
    "Icelandic": "isl_Latn",
    "Irish": "gle_Latn",
    "Welsh": "cym_Latn",
    "Maltese": "mlt_Latn",
    "Albanian": "als_Latn",
    "Macedonian": "mkd_Cyrl",
    "Armenian": "hye_Armn",
    "Georgian": "kat_Geor",
    "Azerbaijani": "azj_Latn",
    "Kazakh": "kaz_Cyrl",
}

TRANSLATE_LANGUAGE_CODE_TO_NAME = {
    code: name for name, code in TRANSLATE_LANGUAGE_MAPPING.items()
}


# Display name -> EasyOCR language code.
EASYOCR_LANGUAGE_MAPPING = {
    "Afrikaans": "af",
    "Arabic": "ar",
    "Assamese": "as",
    "Avar": "ava",
    "Adyghe": "ady",
    "Azerbaijani": "az",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bhojpuri": "bho",
    "Bulgarian": "bg",
    "Braj/Bagri (bgc)": "bgc",
    "Bosnian": "bs",
    "Chechen": "che",
    "Chinese (Simplified)": "ch_sim",
    "Chinese (Traditional)": "ch_tra",
    "Czech": "cs",
    "Welsh": "cy",
    "Danish": "da",
    "Dargwa": "dar",
    "English": "en",
    "Estonian": "et",
    "Persian": "fa",
    "Spanish": "es",
    "French": "fr",
    "Irish": "ga",
    "German": "de",
    "Gom (gom)": "gom",
    "Hindi": "hi",
    "Croatian": "hr",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Ingush": "inh",
    "Icelandic": "is",
    "Italian": "it",
    "Japanese": "ja",
    "Kabardian": "kbd",
    "Kannada": "kn",
    "Korean": "ko",
    "Kurdish": "ku",
    "Lak (lbe)": "lbe",
    "Latin": "la",
    "Lezghian": "lez",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Maithili": "mai",
    "Maori": "mi",
    "Manipuri": "mni",
    "Mongolian": "mn",
    "Marathi": "mr",
    "Malay": "ms",
    "Maltese": "mt",
    "Mah (mah)": "mah",
    "Nepali": "ne",
    "Newari": "new",
    "Dutch": "nl",
    "Norwegian": "no",
    "Occitan": "oc",
    "Pali": "pi",
    "Polish": "pl",
    "Portuguese": "pt",
    "Abaza (abq)": "abq",
    "Romanian": "ro",
    "Russian": "ru",
    "Serbian (Cyrillic)": "rs_cyrillic",
    "Serbian (Latin)": "rs_latin",
    "Sanskrit": "sa",
    "Sakha/Chakma (sck)": "sck",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Albanian": "sq",
    "Swedish": "sv",
    "Swahili": "sw",
    "Tabasaran": "tab",
    "Tamil": "ta",
    "Tajik": "tjk",
    "Tagalog": "tl",
    "Thai": "th",
    "Turkish": "tr",
    "Telugu": "te",
    "Uyghur": "ug",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Nepali/Bhojpuri (bh)": "bh",
    "Angika": "ang",
}

# Display name -> PaddleOCR language code.
PADDLEOCR_LANGUAGE_MAPPING = {
    "English": "en",
    "Chinese (Simplified)": "ch",
    "Chinese (Traditional)": "chinese_cht",
    "Japanese": "japan",
    "Korean": "korean",
    "Thai": "th",
    "Greek": "el",
    "Telugu": "te",
    "Tamil": "ta",
    "Afrikaans": "af",
    "Arabic": "ar",
    "Abaza (abq)": "abq",
    "Adyghe (ady)": "ady",
    "Angika": "ang",
    "Avar": "ava",
    "Azerbaijani": "az",
    "Bashkir (ba)": "ba",
    "Belarusian": "be",
    "Bhojpuri": "bho",
    "Braj/Bagri (bgc)": "bgc",
    "Bulgarian": "bg",
    "Bosnian": "bs",
    "Buryat (bua)": "bua",
    "Catalan": "ca",
    "Chechen": "che",
    "Chuvash (cv)": "cv",
    "Czech": "cs",
    "Welsh": "cy",
    "Danish": "da",
    "Dargwa": "dar",
    "German": "de",
    "Spanish": "es",
    "Estonian": "et",
    "Basque": "eu",
    "Persian": "fa",
    "Finnish": "fi",
    "French": "french",
    "Irish": "ga",
    "Galician": "gl",
    "Gom (gom)": "gom",
    "Hindi": "hi",
    "Croatian": "hr",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Ingush": "inh",
    "Icelandic": "is",
    "Italian": "it",
    "Georgian": "ka",
    "Kazakh (kk)": "kk",
    "Kabardian": "kbd",
    "Kyrgyz (ky)": "ky",
    "Komi (kv)": "kv",
    "Kurdish": "ku",
    "Lak (lbe)": "lbe",
    "Luxembourgish (lb)": "lb",
    "Latin": "la",
    "Lezghian": "lez",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Maithili": "mai",
    "Moksha (mo)": "mo",
    "Macedonian": "mk",
    "Mongolian": "mn",
    "Marathi": "mr",
    "Malay": "ms",
    "Maltese": "mt",
    "Mah (mah)": "mah",
    "Mari (mhr)": "mhr",
    "Nepali": "ne",
    "Dutch": "nl",
    "Norwegian": "no",
    "Occitan": "oc",
    "Ossetian (os)": "os",
    "Pali": "pi",
    "Polish": "pl",
    "Portuguese": "pt",
    "Pashto": "ps",
    "Quechua (qu)": "qu",
    "Romanian": "ro",
    "Romansh (rm)": "rm",
    "Russian": "ru",
    "Sanskrit": "sa",
    "Sakha/Chakma (sck)": "sck",
    "Sindhi": "sd",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Albanian": "sq",
    "Serbian (Cyrillic)": "rs_cyrillic",
    "Serbian (Latin)": "rs_latin",
    "Swedish": "sv",
    "Swahili": "sw",
    "Tabasaran": "tab",
    "Tajik (tg)": "tg",
    "Turkish": "tr",
    "Tatar (tt)": "tt",
    "Tyvan (tyv)": "tyv",
    "Udmurt (udm)": "udm",
    "Uyghur": "ug",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Kalmyk (xal)": "xal",
    "Karakalpak (kaa)": "kaa",
    "Baluchi (bal)": "bal",
    "German (legacy code)": "german",
}
